name: Daily Contribution

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-contribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Update timestamp
        run: |
          echo "Last updated: $(date)" > .last-updated.txt
      
      - name: Commit and push if changed
        run: |
          git add .last-updated.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update timestamp [skip ci]" && git push) 